/**
 * Gemini AMPM — D1 lead_submissions writer
 * -----------------------------------------
 *
 * Single function: `logLead(db, lead)`. Writes one row per form submission
 * to the `lead_submissions` D1 table. Runs in parallel with the Resend send
 * inside `routeLead`, so even a failed Resend produces a row with
 * `send_status='failed'` — there are no silent lost leads. That guarantee
 * is the single biggest deliverability mitigation in the spec's risk
 * register.
 *
 * Local-dev degraded mode
 * -----------------------
 * If `db` is null (because we haven't bound the D1 binding yet in
 * wrangler.toml / env.d.ts — see `LEAD_DB` commented out in env.d.ts),
 * we log a structured `{ leadLogFallback: ... }` line to console instead.
 * That keeps the dev loop unblocked while the D1 instance is being
 * provisioned, without ever throwing into the action handler.
 *
 * Schema
 * ------
 * Run this once against the prod + preview D1 instances before going live:
 *
 *   CREATE TABLE IF NOT EXISTS lead_submissions (
 *     id              TEXT PRIMARY KEY,
 *     ts              TEXT NOT NULL,                 -- ISO 8601 UTC
 *     form_type       TEXT NOT NULL,                 -- consult|quote|maintenance
 *     pillar          TEXT NOT NULL,                 -- gas-suppression etc.
 *     source          TEXT NOT NULL,                 -- hero|gate|primary|maintenance|footer
 *     variant_id      TEXT NOT NULL DEFAULT 'A',
 *     page_path       TEXT NOT NULL,
 *     name            TEXT NOT NULL,
 *     email           TEXT NOT NULL,
 *     phone           TEXT,
 *     company         TEXT,
 *     role            TEXT,
 *     postcode        TEXT,
 *     space_type      TEXT,
 *     approx_area_sqm INTEGER,
 *     current_system  TEXT,
 *     message         TEXT,
 *     file_upload_key TEXT,
 *     utm_source      TEXT,
 *     utm_medium      TEXT,
 *     utm_campaign    TEXT,
 *     mailbox         TEXT,                          -- resolved destination
 *     send_status     TEXT NOT NULL,                 -- sent|failed|skipped
 *     send_error      TEXT,                          -- Resend error if failed
 *     resend_id       TEXT                           -- Resend message id if sent
 *   );
 *
 *   CREATE INDEX IF NOT EXISTS idx_lead_pillar_ts ON lead_submissions (pillar, ts);
 *   CREATE INDEX IF NOT EXISTS idx_lead_send_status ON lead_submissions (send_status);
 *
 * Spec ref:
 *   /Users/jamiedawson/Documents/Claude/Projects/Gemini AMPM/01-website/
 *     audits/SERVICE_VERTICAL_TEMPLATE.md — § "Forms Wiring", step 5 of
 *     routeLead(): "Parallel D1 write to `lead_submissions` [...]
 *     Failed Resend send = D1 row with send_status='failed' — guarantees
 *     no silent lost lead."
 */

import type { FormType } from './mailbox-routing';

/**
 * Minimal D1 surface we depend on. Mirrors `@cloudflare/workers-types`
 * `D1Database` so we can swap to the real type once the binding lands
 * in env.d.ts (currently commented out) without code changes here.
 */
export interface D1Database {
  prepare(query: string): D1PreparedStatement;
}

export interface D1PreparedStatement {
  bind(...values: unknown[]): D1PreparedStatement;
  run(): Promise<unknown>;
}

export type SendStatus = 'sent' | 'failed' | 'skipped';

export interface LeadRow {
  /** UUID v4 generated by the orchestrator (used as row PK + idempotency key). */
  id: string;
  /** ISO 8601 UTC timestamp. */
  ts: string;
  formType: FormType;
  pillar: string;
  source: string;
  variantId: string;
  pagePath: string;

  // Contact details (sparse — only populated where the form collected them)
  name: string;
  email: string;
  phone?: string;
  company?: string;
  role?: string;
  postcode?: string;
  spaceType?: string;
  approxAreaSqm?: number;
  currentSystem?: string;
  message?: string;
  fileUploadKey?: string;

  // Attribution
  utmSource?: string;
  utmMedium?: string;
  utmCampaign?: string;

  // Send result
  mailbox?: string;
  sendStatus: SendStatus;
  sendError?: string;
  resendId?: string;
}

const INSERT_SQL = `
  INSERT INTO lead_submissions (
    id, ts, form_type, pillar, source, variant_id, page_path,
    name, email, phone, company, role, postcode, space_type,
    approx_area_sqm, current_system, message, file_upload_key,
    utm_source, utm_medium, utm_campaign,
    mailbox, send_status, send_error, resend_id
  ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`;

/**
 * Persist a lead row. Never throws — D1 failures are caught and logged so
 * the action handler returns a clean envelope to the client.
 *
 * @param db   - D1Database binding, or null in local-dev degraded mode.
 * @param lead - Fully resolved lead row, including send_status.
 */
export async function logLead(
  db: D1Database | null,
  lead: LeadRow,
): Promise<{ ok: boolean; error?: string }> {
  if (!db) {
    // Local-dev fallback: structured console log so we can grep `leadLogFallback`
    // when verifying the form wiring end-to-end without a live D1 binding.
    console.log('leadLogFallback', JSON.stringify(lead));
    return { ok: true };
  }

  try {
    await db
      .prepare(INSERT_SQL)
      .bind(
        lead.id,
        lead.ts,
        lead.formType,
        lead.pillar,
        lead.source,
        lead.variantId,
        lead.pagePath,
        lead.name,
        lead.email,
        lead.phone ?? null,
        lead.company ?? null,
        lead.role ?? null,
        lead.postcode ?? null,
        lead.spaceType ?? null,
        lead.approxAreaSqm ?? null,
        lead.currentSystem ?? null,
        lead.message ?? null,
        lead.fileUploadKey ?? null,
        lead.utmSource ?? null,
        lead.utmMedium ?? null,
        lead.utmCampaign ?? null,
        lead.mailbox ?? null,
        lead.sendStatus,
        lead.sendError ?? null,
        lead.resendId ?? null,
      )
      .run();
    return { ok: true };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('d1LeadInsertFailed', message, JSON.stringify(lead));
    return { ok: false, error: message };
  }
}
